### ISSUE TITLE
Create dropdowns for navigation bar

### ISSUE THREAD

**Issue by misspokeycat** [exewebdev/exe#12]
We need the navigation bar to list all the projects for the project button.

**Comment by rz1005** [comment]
Dude, 
Don't sweat the small stuff. Leave something for the others and me to do.  You have more important things to work on.

**Comment by rz1005** [comment]
Kevin and I will take this one.

**Comment by misspokeycat** [comment]
Feature has been implemented; closing.

**Comment by pokemonmegaman** [comment]
Feature has been implemented; closing.

**Comment by pokemonmegaman** [comment]
Feature has been implemented; closing.
