### ISSUE TITLE
Join.html no longer calls functions in the body tag

### ISSUE THREAD

**Issue by rz1005** [exewebdev/exe#29]
Ahem,

someone removed some function calls in the body tag when switching to using the template engine.

**Comment by misspokeycat** [comment]
Which function calls are we referring to here?  I can add them back in.

**Comment by misspokeycat** [comment]
also, if page specific scripts are needed, you can use the `{head}` block in templates to add in more stylesheets and scripts

**Comment by rz1005** [comment]
I need these function calls to be called when the user is navigating away/to a webpage. That's why I put them in the body tag.. The previous body tag:

```
<body onpagehide="initStorage()" onpageshow="loadStorage()">
```

**Comment by misspokeycat** [comment]
Should this be sitewide or just for the join page?

EDIT: IT seems like it is just for the join page.  The easiest way to get back this funtionality is by adding a script with

`$('body').onpagehide = function(){initStorage()};`

`$('body').onpageshow = function(){loadStorage()};`

to the join page.

**Comment by rz1005** [comment]
just the join page.  Thanks for showing me how to do it in a script.

**Comment by misspokeycat** [comment]
Seems this was added, closing.
